services:
  _defaults:
      autowire: true
      autoconfigure: true

  Fasano\FormsBundle\Form\:
    resource: '../../Form/'

  Fasano\FormsBundle\Form\FormTypeClassFactory:
      arguments:
          $cacheDir: '%kernel.cache_dir%/'
          $enableCache: '%env(bool:not:APP_DEBUG)%'